name: johnmichaelcooper
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#323232'
    - '#707070'
    - '#bbbbbb'
    - '#d5d5d5'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.48058093222789466
  rhythmicContrast: 0.03955853567458689
purpose: []
